language: php
dist: trusty
os: linux

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  if [[ "$DB" == "mysql" ]]; then mysql -e 'DROP DATABASE IF EXISTS `pragma-core`; CREATE DATABASE `pragma-core`;'; fi;
  if [[ "$DB" == "postgresql" ]]; then psql -c 'DROP DATABASE IF EXISTS "pragma_core";' -U postgres; psql -c 'CREATE DATABASE "pragma_core";' -U postgres; psql pragma_core -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"' -U postgres; fi;

install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer install --no-interaction --quiet --optimize-autoloader
script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.config.$DB.php tests/
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.config.$DB.uidmysql.php tests/
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.config.$DB.uidphp.php tests/
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - env: DB=sqlite
      php: '7.0'
    - env: DB=sqlite
      php: '7.1'
    - env: DB=sqlite
      php: '7.2'
    - env: DB=sqlite
      php: '7.3'
    - env: DB=sqlite
      php: '7.4'
    - env: DB=sqlite
      php: 'nightly'
    - env: DB=postgresql
      services: postgresql
      php: '7.0'
    - env: DB=postgresql
      services: postgresql
      php: '7.1'
    - env: DB=postgresql
      services: postgresql
      php: '7.2'
    - env: DB=postgresql
      services: postgresql
      php: '7.3'
    - env: DB=postgresql
      services: postgresql
      php: '7.4'
    - env: DB=postgresql
      services: postgresql
      php: 'nightly'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.2'
      php: '7.0'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.2'
      php: '7.1'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.2'
      php: '7.2'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.2'
      php: '7.3'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.2'
      php: '7.4'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.2'
      php: 'nightly'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.5'
      php: '7.0'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.5'
      php: '7.1'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.5'
      php: '7.2'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.5'
      php: '7.3'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.5'
      php: '7.4'
    - env: DB=mysql
      services: mysql
      addons:
        mariadb: '10.5'
      php: 'nightly'
