language: php
dist: trusty
os: linux

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
    if [[ "$DB" == "mysql" ]]; then mysql -e 'DROP DATABASE IF EXISTS pragma-core; CREATE DATABASE `pragma-core`;'; fi;
    if [[ "$DB" == "postgresql" ]]; then psql -c 'DROP DATABASE IF EXISTS pragma-core; CREATE DATABASE "pragma_core";' -U postgres; psql pragma_core -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"' -U postgres; fi;
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - 'nightly'
env:
  - DB=sqlite
  - DB=postgresql
  - DB=maria101
  - DB=maria102
install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - composer install --no-interaction --quiet --optimize-autoloader
script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.config.$DB.php tests/
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.config.$DB.uidmysql.php tests/
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.config.$DB.uidphp.php tests/
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - if: env(DB) = maria101
      env:
        DB=mysql
      addons:
        mariadb: '10.2'
    - if: env(DB) = maria102
      env:
        DB=mysql
      addons:
        mariadb: '10.2'
