language: php
dist: trusty

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
    if [[ "${DB:0:5}" == "mysql" ]]; then mysql -e 'CREATE DATABASE `pragma-core`;'; fi;
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
env:
  - DB=sqlite
  - DB=sqlite.uidmysql
  - DB=sqlite.uidphp
install: composer install --no-interaction --quiet --optimize-autoloader
script:
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.config.$DB.php tests/

jobs:
  allow_failures:
    - php: nightly

  include:
      - stage: Test php7.0 & mariadb
        php: 7.0
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.1'
      - stage: Test
        php: 7.0
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.2'

      - stage: Test php7.1 & mariadb
        php: 7.1
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.1'
      - stage: Test
        php: 7.1
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.2'

      - stage: Test hhvm & mariadb
        php: hhvm
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.1'
      - stage: Test
        php: hhvm
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.2'

      - stage: Test php nightly & mariadb
        php: nightly
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.1'
      - stage: Test
        php: nightly
        services:
          - mysql
        env:
          - DB=mysql
          - DB=mysql.uidmysql
          - DB=mysql.uidphp
        addons:
            mariadb: '10.2'
